# Generated by Django 3.2 on 2023-04-25 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvbhrs1gf/image/upload/v1682439593/WebP_File_Format_qjtvp8.png', max_length=255, verbose_name='Package Image'),
        ),
    ]
