# Generated by Django 3.2 on 2023-04-25 20:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='image_url',
        ),
        migrations.AddField(
            model_name='packages',
            name='photo_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dvbhrs1gf/image/upload/v1682439593/WebP_File_Format_qjtvp8.png', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Package Image'),
        ),
    ]
