# Generated by Django 3.2 on 2023-04-25 20:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_rename_photo_url_packages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvbhrs1gf/image/upload/v1682163967/poster_z6vm8x_ap9dde.webp', max_length=255, verbose_name='Package Image'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
