# Generated by Django 3.2 on 2023-04-25 21:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20230425_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvbhrs1gf/image/upload/v1682103480/techno-tech2_ytmx35.png', max_length=255, verbose_name='Package Image'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
